//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuitoPassport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUDITORIA()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID_AUDITORIA { get; set; }
        public Nullable<int> EXITOSOS { get; set; }
        public Nullable<int> FALLIDOS { get; set; }
        public Nullable<int> NOAUTORIZADOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
