//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuitoPassport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_ROL { get; set; }
        public int ID_AUDITORIA { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_ESTADO { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string CONTRASENA { get; set; }
    
        public virtual AUDITORIA AUDITORIA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
